services:
  redis:
    image: docker.io/bitnami/redis:7.4.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - "6379"

  mitserver:
    build:
      context: .
    image: "ghcr.io/ksysoev/make-it-public:${MIT_VERSION:-latest}"
    restart: unless-stopped
    container_name: mitserver
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
      - target: 8082
        published: 8082
        protocol: tcp
        mode: host
      - target: 10000-10999
        published: 10000-10999
        protocol: tcp
        mode: host
    environment:
      - AUTH_REDIS_ADDR=redis:6379
      - AUTH_SALT=${AUTH_SALT:-someRandomSalt}
      - "AUTH_KEY_PREFIX=MIT::"
      - HTTP_PUBLIC_SCHEMA=https
      - HTTP_PUBLIC_DOMAIN=${DOMAIN_NAME:-make-it-public.dev}
      - HTTP_LISTEN=:8080
      - HTTP_CONN_LIMIT=${HTTP_CONN_LIMIT:-32}
      - HTTP_PROXY_PROTO=true
      - REVERSE_PROXY_LISTEN=:8081
      - REVERSE_PROXY_CERT=/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DOMAIN_NAME}/${DOMAIN_NAME}.crt
      - REVERSE_PROXY_KEY=/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DOMAIN_NAME}/${DOMAIN_NAME}.key
      - API_LISTEN=:8082
      - LOG_LEVEL=info
      - LOG_TEXT=false
      - TCP_LISTEN_HOST=0.0.0.0
      - TCP_PUBLIC_HOST=${DOMAIN_NAME:-make-it-public.dev}
      - TCP_PORT_RANGE_MIN=${TCP_PORT_RANGE_MIN:-10000}
      - TCP_PORT_RANGE_MAX=${TCP_PORT_RANGE_MAX:-10999}
    command: ["server", "run", "all" ]
    volumes:
      - caddy_data:/data:ro
    healthcheck:
      test: ["CMD", "/mit",  "server", "check"]
    depends_on:
      - redis


  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:2.10-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      # listen on host ports without ingress network
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - EMAIL=${EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./runtime/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mitserver

volumes:
  caddy_data:
  caddy_config:
  redis_data:

networks:
  default:
    external: true
    name: ${NETWORK_NAME:-mit-network}
